/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import AllTableModels.IssueBookTableModel;
import entity.Author;
import entity.Book;
import entity.Student;
import java.sql.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import services.CommonService;
import services.StudentService;

/**
 *
 * @author suhail
 */
public class IssueBookForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form IssueBookForm
     */
    private CommonService commonService;
    
    private Vector<Author> vectorAuthors;

    private Vector<Book> vectorBook;

    private StudentService studentService;
    
    public IssueBookForm() {
        initComponents();
        
        studentService = new StudentService();
        
        commonService = new CommonService();
        
        vectorAuthors = commonService.getVectorAuthors();
        DefaultComboBoxModel modelAuthor = new DefaultComboBoxModel(vectorAuthors);
        cmbSelectAuthor.setModel(modelAuthor);

        vectorBook = new Vector<Book>();

        long currentTimeMilli = System.currentTimeMillis();
        System.out.println(currentTimeMilli);

        Date date = new Date(currentTimeMilli);

        jdDateChooser.setDate(date);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        cmbSelectAuthor = new javax.swing.JComboBox<>();
        cmbSelectEdition = new javax.swing.JComboBox<>();
        txtRegistrationNo = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbSelectBook = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtFatherName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnDeleteRow = new javax.swing.JButton();
        btnClearList = new javax.swing.JButton();
        jdDateChooser = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Issue Book Form");

        jLabel1.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        jLabel1.setText("Registration No#");

        jLabel2.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        jLabel2.setText("Select Author");

        jLabel3.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        jLabel3.setText("Select Edition");

        jLabel4.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        jLabel4.setText("Search Author");

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        cmbSelectAuthor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSelectAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectAuthorActionPerformed(evt);
            }
        });

        cmbSelectEdition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSelectEdition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectEditionActionPerformed(evt);
            }
        });

        txtRegistrationNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegistrationNoActionPerformed(evt);
            }
        });
        txtRegistrationNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRegistrationNoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRegistrationNoKeyReleased(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        btnAdd.setText("+");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        jLabel5.setText("Select Book");

        jLabel6.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        jLabel6.setText("Student Name");

        cmbSelectBook.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSelectBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectBookActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        jLabel7.setText("Father Name");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnDeleteRow.setText("Delete Row");
        btnDeleteRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRowActionPerformed(evt);
            }
        });

        btnClearList.setText("Clear List");
        btnClearList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addComponent(btnDeleteRow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClearList)
                        .addGap(136, 136, 136))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtRegistrationNo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbSelectEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbSelectAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel5))
                                                .addGap(29, 29, 29))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtFatherName, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                            .addComponent(txtStudentName, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                            .addComponent(cmbSelectBook, 0, 168, Short.MAX_VALUE)
                                            .addComponent(jdDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(102, 102, 102)))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegistrationNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSelectBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSelectAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbSelectEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteRow)
                    .addComponent(btnClearList))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void cmbSelectBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectBookActionPerformed
        Book book = (Book) cmbSelectBook.getSelectedItem();

        Vector<String> vectorEdition;
        vectorEdition = commonService.getVectorEdition(book);
        DefaultComboBoxModel modelEdition = new DefaultComboBoxModel(vectorEdition);
        cmbSelectEdition.setModel(modelEdition);
    }//GEN-LAST:event_cmbSelectBookActionPerformed

    private void cmbSelectAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectAuthorActionPerformed
        Author author = (Author) cmbSelectAuthor.getSelectedItem();

        Vector<Book> vectorBooks;
        vectorBooks = commonService.getVectorBooks(author);
        DefaultComboBoxModel modelBooks = new DefaultComboBoxModel(vectorBooks);
        cmbSelectBook.setModel(modelBooks);
    }//GEN-LAST:event_cmbSelectAuthorActionPerformed

    private void txtRegistrationNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegistrationNoKeyReleased

    }//GEN-LAST:event_txtRegistrationNoKeyReleased

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String authorName = txtSearch.getText();
        vectorAuthors = commonService.getVectorAuthors(authorName);
        DefaultComboBoxModel modelAuthor = new DefaultComboBoxModel(vectorAuthors);
        cmbSelectAuthor.setModel(modelAuthor);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtRegistrationNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegistrationNoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistrationNoKeyPressed

    private void btnDeleteRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRowActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        vectorBook.removeElementAt(selectedRow);
        IssueBookTableModel issueTableModel = new IssueBookTableModel(vectorBook);
        jTable1.setModel(issueTableModel);
    }//GEN-LAST:event_btnDeleteRowActionPerformed

    private void btnClearListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearListActionPerformed
        vectorBook.removeAllElements();
        IssueBookTableModel issueBookTable = new IssueBookTableModel(vectorBook);
        jTable1.setModel(issueBookTable);
    }//GEN-LAST:event_btnClearListActionPerformed

    private void cmbSelectEditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectEditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSelectEditionActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Author author = (Author) cmbSelectAuthor.getSelectedItem();
        Book book = (Book) cmbSelectBook.getSelectedItem();
        String edition = cmbSelectEdition.getSelectedItem().toString();

        book.setEdition(edition);
        //         book.getAuthor().getAuthorName();
        book.setAuthor(author);

        vectorBook.add(book);
        IssueBookTableModel issueBookTable = new IssueBookTableModel(vectorBook);
        jTable1.setModel(issueBookTable);

    }//GEN-LAST:event_btnAddActionPerformed

    private void txtRegistrationNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistrationNoActionPerformed
        Student student = new Student();

        String registrationNo = txtRegistrationNo.getText();
        if (registrationNo.equals("")) {
            JOptionPane.showMessageDialog(null, "Empty data cannot be shown");
        } else {
            student = commonService.StudentSearch(registrationNo);
        }
        txtStudentName.setText(student.getStudentName());
        txtFatherName.setText(student.getFatherName());
    }//GEN-LAST:event_txtRegistrationNoActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        String registrationNumber = txtRegistrationNo.getText();

        int year = jdDateChooser.getCalendar().get(1);
        int day = jdDateChooser.getCalendar().get(5);
        int month = jdDateChooser.getCalendar().get(2) + 1;

        String currentMonth = "";
        String currentDay = "";

        if (day < 10) {
            currentDay = "0" + day;
        } else {
            currentDay = "" + day;
        }
        if (month < 10) {
            currentMonth = "0" + month;
        } else {
            currentMonth = "" + month;
        }

        String selectedDate = year + "-" + currentMonth + "-" + currentDay;
        
        studentService.issueBooks(vectorBook, registrationNumber, selectedDate);

    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClearList;
    private javax.swing.JButton btnDeleteRow;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbSelectAuthor;
    private javax.swing.JComboBox<String> cmbSelectBook;
    private javax.swing.JComboBox<String> cmbSelectEdition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser jdDateChooser;
    private javax.swing.JTextField txtFatherName;
    private javax.swing.JTextField txtRegistrationNo;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStudentName;
    // End of variables declaration//GEN-END:variables
}
